### ISSUE TITLE
Guardian ranks

### ISSUE THREAD

**Issue by TenDRILLL** [TenDRILLL/Argos#12]
Should look into implementing Guardian Ranks as one of the logged parameters into Argos.

Definition of Done:
- [x] API Mappings typed
- [x] Guardian Rank values saved to user information
- [x] Decide if GR should be visible on Discord Connection
- [x] If so, implemented

**Comment by Ugi0** [comment]
I would personally rather have it be the current guardian rank since lifetime highest might not be accurate for someone who hasn't played for a few season for example.
Would be great to have the guardian rank be the same as ingame. GR should be visible in discord connection imo

**Comment by TenDRILLL** [comment]
Fair, we implement current then

**Comment by TenDRILLL** [comment]
Implemented in: 55579000ff5970535287967bc0a7884b35a7424e
Testing...
