### ISSUE TITLE
XUR embed autopost

### ISSUE THREAD

**Issue by TenDRILLL** [TenDRILLL/Argos#15]
Given we have automatized the XUR embed creation, we could also automatize posting it to the related channel on Discord.
Would need to store a reference to the already sent message to avoid spamming.

Definition of Done:
- [x] Config value for channel ID
- [x] #23
- [x] Sending implemented
- [ ] Checking previous message implemented
- [ ] XUR Embed posted on Discord once a week to the defined channel

**Comment by Ugi0** [comment]
498e88f implemented
