### ISSUE TITLE
Allow user to unregister

### ISSUE THREAD

**Issue by TenDRILLL** [TenDRILLL/Argos#18]
Right now there's no automated method of unregistering and therefore developers have to manually delete your data if you so choose.
We should implement a solution for this.

**Comment by Ugi0** [comment]
Would the unregistering be better to be done with a command or through the panel site?

**Comment by TenDRILLL** [comment]
> Would the unregistering be better to be done with a command or through the panel site?

Why not both?

**Comment by Ugi0** [comment]
2f34a0d implements unregistering through both panel and a command
