### ISSUE TITLE
ActivityIdentifier DB not updating

### ISSUE THREAD

**Issue by TenDRILLL** [TenDRILLL/Argos#21]
New dungeon was released and it was missing from all Argos functionalities.

**Comment by TenDRILLL** [comment]
According to @Ugi0 the Act Id DB works just fine, bot just hadn't restarted to accommodate for changes.
We should implement reloading DBs at constant intervals to avoid manual restarting of Argos.

**Comment by Ugi0** [comment]
I would prefer having a command that will run the updateActivityIdentifierDB. Command should only be accessible to admins, if possible. Commit 06caa46 implements the command. Remove if solution is not preferable

**Comment by TenDRILLL** [comment]
Should defer reply incase updating takes too long...

**Comment by TenDRILLL** [comment]
nvm since it doesn't actually return the status of the update, I guess this is fine
